version: '3.9'
name: uaspakso

services:
  web:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "8080:80"
    networks:
      - app_network
    volumes:
      - ./nginx:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Mount file konfigurasi Nginx

  database:
    image: mysql:latest
    container_name: mysql_database
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepassword
    ports:
      - "3306:3306"
    networks:
      - app_network
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf  # Mount file konfigurasi MySQL

  message_queue:
    image: redis:latest
    container_name: redis_queue
    ports:
      - "6379:6379"
    networks:
      - app_network
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf  # Mount file konfigurasi Redis

networks:
  app_network:
    driver: bridge

volumes:
  db_data: